# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mini-capstone_development


test:
  <<: *default
  database: mini-capstone_test


#
production:
  <<: *default
  database: mini-capstone_production
  username: mini-capstone
  password: <%= ENV['MINI-CAPSTONE_DATABASE_PASSWORD'] %>