# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b484061cf28b22e16b00f9b311882ca027c576cf64301a46fff90faa2affb9b74724828fa8266a25c711192c31b7efecf1cab039dd70439572cddb6548715849

test:
  secret_key_base: 063f648204138ecb0a6287bf519b914b9708fa1276c318cdd9514424bd7b626498ceeee143fd7c467ce94696d382d6caf97630fccf56bd66a3f02884f730ffab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
